# Generated by Django 3.1.7 on 2021-03-12 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0017_auto_20181209_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 12, 10, 25, 42, 870333, tzinfo=utc)),
        ),
    ]
